targets:
  $default:
    builders:
      graphql_codegen:
        options:
          # Location of GraphQL schema
          schema: lib/schema/schema.graphql

          # GraphQL query files
          queries: lib/graphql/**/*.graphql

          # Scalar mappings
          scalars:
            Time:
              type: DateTime

          # Clients to generate
          clients:
            - graphql
      riverpod_generator:
        options:
          # Generate riverpod providers
          line_length: 80
      json_serializable:
        options:
          # JSON serialization options
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true