name: clubland
description: "Premium End User Flutter application for the Reciprocal Clubs platform"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Navigation
  go_router: ^12.1.3

  # HTTP & GraphQL
  dio: ^5.4.0
  graphql_flutter: ^5.1.2
  gql: ^0.14.0

  # Authentication & Security
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.7
  crypto: ^3.0.3

  # Local Storage & Caching
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2

  # UI & UX
  cached_network_image: ^3.3.0
  lottie: ^2.7.0
  shimmer: ^3.0.0
  photo_view: ^0.14.0
  smooth_page_indicator: ^1.1.0
  flutter_staggered_animations: ^1.1.1

  # Maps & Location
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  # Push Notifications
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.8
  firebase_performance: ^0.9.3+6

  # Permissions
  permission_handler: ^11.1.0

  # Utils
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  intl: ^0.18.1
  uuid: ^4.2.1
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.1
  connectivity_plus: ^5.0.2

  # QR Codes
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.2

  # Image Processing
  image_picker: ^1.0.4
  image_cropper: ^5.0.1

  # Icons & Fonts
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

  # Development Utilities
  logger: ^2.0.2
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

  # GraphQL Code Generation
  graphql_codegen: ^0.13.3

  # Testing
  mocktail: ^1.0.2
  golden_toolkit: ^0.15.0
  alchemist: ^0.7.0

  # Code Quality
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0

# Hive Type Adapters
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/logos/

  fonts:
    - family: ClublandIcons
      fonts:
        - asset: assets/fonts/ClublandIcons.ttf

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated/l10n

dependency_overrides:
  # Override any problematic dependencies if needed
