// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'app_router.dart';

// **************************************************************************
// RiverpodGenerator
// **************************************************************************

// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, type=warning
/// Provides the configured [GoRouter] instance.
///
/// This provider is generated by Riverpod and handles the entire routing logic,
/// including authentication redirects via [RouteGuards.redirect].

@ProviderFor(appRouter)
const appRouterProvider = AppRouterProvider._();

/// Provides the configured [GoRouter] instance.
///
/// This provider is generated by Riverpod and handles the entire routing logic,
/// including authentication redirects via [RouteGuards.redirect].

final class AppRouterProvider
    extends $FunctionalProvider<GoRouter, GoRouter, GoRouter>
    with $Provider<GoRouter> {
  /// Provides the configured [GoRouter] instance.
  ///
  /// This provider is generated by Riverpod and handles the entire routing logic,
  /// including authentication redirects via [RouteGuards.redirect].
  const AppRouterProvider._()
    : super(
        from: null,
        argument: null,
        retry: null,
        name: r'appRouterProvider',
        isAutoDispose: true,
        dependencies: null,
        $allTransitiveDependencies: null,
      );

  @override
  String debugGetCreateSourceHash() => _$appRouterHash();

  @$internal
  @override
  $ProviderElement<GoRouter> $createElement($ProviderPointer pointer) =>
      $ProviderElement(pointer);

  @override
  GoRouter create(Ref ref) {
    return appRouter(ref);
  }

  /// {@macro riverpod.override_with_value}
  Override overrideWithValue(GoRouter value) {
    return $ProviderOverride(
      origin: this,
      providerOverride: $SyncValueProvider<GoRouter>(value),
    );
  }
}

String _$appRouterHash() => r'1dfe41d4af140d42b6ada09c604cdce287db2359';
